config/routes.rb
Rails.application.routes.draw do
 
  root 'depts#index'
  resources :depts do 
    resources :items 
  end 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dept.rb
class Dept < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :dept
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/depts_controller.rb
class DeptsController < ApplicationController
  before_action :set_dept, only: [:show, :update, :edit, :destroy]
  def index
    @depts = Dept.all 
  end

  def show
  end 

  def new
    @dept = Dept.new 
  end



  def create 
    @dept = Dept.create(dept_params)

    if @dept.save
      redirect_to root_path
    else 
      render :new 
    end 

  end 

  

  def edit
  end

  private 

    def set_dept 
      @dept = Dept.find(params[:id])
    end 

    def dept_params 
      params.require(:dept).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_dept
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  def index
    @items = @dept.items
  end

  def show 
  end 

  def new
    @item = @dept.items.new
    render partial: 'form'
  end

  def edit
    render partial: "form"
  end

  def create 
    @item = @dept.items.new(item_params)

    if @item.save
      redirect_to dept_items_path[@dept, @item]
    else 
      render :new 
    end 
  end 


  private 

  def set_item 
    @item = Item.find(params[:id])
  end 

  def set_dept 
    @dept = Dept.find(params[:dept_id])
  end 

  def item_params
    params.require(:item).permit(:name, :desc, :img, :price)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/depts/_form.html.erb
<%= form_for @dept do |f| %> 
  <%= f.label :name %> 
  <%= f.text_field :name, required: true, autofocus: true %> 
  <br /> 
  <%= f.submit %> 
<% end %> 

app/views/depts/edit.html.erb
<h1>Depts#edit</h1>
<p>Find me in app/views/depts/edit.html.erb</p>

app/views/depts/index.html.erb
<h1>Welcome to the Super Store</h1>
<h3>Check out a Department to see items</h3>
<%= link_to 'Create New Department', new_dept_path %> 
<ul>
  <% @depts.each do |dept| %> 
    <li>
      <h2><%= link_to dept.name, dept%></h2>
    </li>
  <% end %> 
</ul>

app/views/depts/new.html.erb
<h1>New Department</h1>
<%= render 'form' %> 

app/views/depts/show.html.erb
<h1>
  <%= @dept.name %>
</h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Items', dept_items_path(@dept) %>
  <br />
  <%= link_to 'Edit Dept', edit_dept_path(@dept) %>
  <br />
  <%= link_to 'Delete Dept', @dept, method: :delete %>
  

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr /> 
<%= form_for [@dept, @item] do |f| %> 
  <%= f.label :name %> 
  <%= f.text_field :name, required: true, autofocus: true %> 
  <br /> 
  <%= f.label :desc %> 
  <%= f.text_area :desc, required: true %> 
  <br /> 
  <%= f.label :price %> 
  <%= f.text_field :price, require: true %> 
  <br /> 
  <%= f.label :image %> 
  <%= f.text_field :img, require: true %> 
  <br /> 
  <%= f.submit %> 
<% end %> 

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1><%= @dept.name %></h1>

<%= link_to 'Create New Item', new_dept_item_path(@dept) %> 
<div>
  <% @items.each do |i| %>
    <div>
      <img src="<%= i.img %>" alt='itm' height=200px> 
      <h3><%= i.name %></h3>
      <h4>Price: $<%= i.price %></h4>
      <h4>Description:</h4>
      <p><%= i.desc %></p>

    </div>
    
  <% end %> 
</div>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1>Show</h1>

app/views/layouts/_nav.html.erb
<%= link_to 'All Departments', root_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>